Feature add UI profile photo in profilesettings #24
hatchways/team-bruschetta pull request #46
Opened 2021-10-17 01:14 UTC by Zorba11

### What this PR does (required):
- list PR functionality here
- UI for uploading profile photo

### Screenshots / Videos (front-end only):
- [](url)

### Any information needed to test this feature (required):

1. run the react app locally
2. login with credentials 
3. goto `localhost:3000/settings` you can see the UI

### Any issues with the current functionality (optional):

1. There is a bug fix related to routing. Please check that as well, I might be wrong (Login.tsx & useAuthContext.tsx)
2. As said in during the standup I've accidentally started building the NavBart and the SideDraw components. I'll be using the same code in a future ticket. for now I'm committing & deleting those components for future reference.

![Screen Shot 2021-10-16 at 7 02 06 PM](https://user-images.githubusercontent.com/42471478/137606240-d161cca2-2096-4a64-a069-02cd4c25bdd5.png)
![Screen Shot 2021-10-16 at 7 02 40 PM](https://user-images.githubusercontent.com/42471478/137606245-fdaa4003-53b7-4915-8509-c24c6c3bf066.png)
e

2021-10-17 01:22 UTC, Zorba11 commented on client/src/components/PhotoUpload/PhotoUpload.tsx
> +import avatarImage from '../../Images/b1f0e680702e811aa8ba333cb19c0e0ea95e8e31.png';
This is just a place holder image until `Setup/IN: Amazon S3 or Cloudinary #41` is done.

2021-10-17 08:57 UTC, ezeilo-su reviewed
This one looks good! Just a minor comment below.
Happy coding!

2021-10-17 08:57 UTC, ezeilo-su commented on client/src/components/PhotoUpload/useStyles.ts
> +      // top: '80%',
Remove unused code

2021-10-17 08:57 UTC, ezeilo-su commented on client/src/pages/ProfileSettings/ProfileSettings.test.tsx
> +});
:+1:

2021-10-17 16:28 UTC, Zorba11 commented on client/src/components/PhotoUpload/useStyles.ts
> +      // top: '80%',
@ezeilo-su sorry about that. will do ! thank you !

2021-10-17 16:38 UTC, Zorba11 commented on client/src/components/PhotoUpload/useStyles.ts
> +      // top: '80%',
Hi, just made the change

2021-10-19 02:25 UTC, rajivtitus commented on client/src/components/PhotoUpload/PhotoUpload.tsx
> +  const infoString = 'Be sure to use a photo that clearly shows your face';
👍🏽

2021-10-19 02:29 UTC, rajivtitus commented on client/src/pages/ProfileSettings/ProfileSettings.tsx
> +    <div className={classes.root}>
You can consider using the MUI 'Box' component here :)

Ref: https://mui.com/components/box/

Eg: `<Box display="flex" alginItems="center"....`

2021-10-19 02:32 UTC, rajivtitus commented on client/src/components/PhotoUpload/PhotoUpload.tsx
> +      <Typography variant="body2" className={classes.title}>
Optional: For increase semantics you can include the content within the 'CardContent' component and the actions within the 'CardActions' component :)

2021-10-19 02:36 UTC, rajivtitus requested changes
Great work! The UI on this looks good, just a couple of minor comments to address.
Some comments have been labelled as 'optional', you can make a decision to implement these changes if it's not too time intensive :)

2021-10-19 02:37 UTC, rajivtitus approved these changes

2021-10-19 16:29 UTC, Zorba11 commented on client/src/pages/ProfileSettings/ProfileSettings.tsx
> +    <div className={classes.root}>
👍

2021-10-19 16:49 UTC, merged